// Generated by CoffeeScript 1.6.3
(function() {
  var growls;

  $(':not(.s-modal)').not('.s-modal *').click(function() {
    return $('.s-modal[style="display: block;"]').fadeOut('fast');
  }).children().click(function(e) {
    if ($('.s-modal[style="display: block;"]').length > 0) {
      return false;
    }
  });

  $('.s-modal .s-close').click(function() {
    return $(this).closest('.s-modal').fadeOut();
  });

  $.fn.s_endconcat = function() {
    var e;
    try {
      return this.each(function() {
        return $(this).html($(this).html().replace(new RegExp('((?:[^ ]* ){' + ($(this).html().match(/\s/g).length - 1) + '}[^ ]*) '), "$1&nbsp;"));
      });
    } catch (_error) {
      e = _error;
      return false;
    }
  };

  $('.s-endconcat').s_endconcat();

  growls = "[class^=\"s-growls-growl\"]";

  (function($) {
    $("body").append("<div id=\"s-growls\" style=\"z-index:2000;position:fixed;width:250px;top:20px;right:20px;overflow:auto;pointer-events:none;\"></div>");
    return $.extend({
      sGrowl: function(options) {
        var defaults, fn, xHtml, _;
        defaults = {
          delay: 0,
          type: "green",
          container: "#s-growls",
          text: "",
          "class": ""
        };
        _ = $.extend(defaults, options);
        _.fTitle = (_.title ? "<strong>" + _.title + "</strong>" : "");
        _.fText = (_.text ? "<p>" + _.text + "</p>" : "");
        this.id = Math.floor(Math.random() * 1000);
        this.html = document.createElement("div");
        this.html.className = "s-growls-growl s-growls-growl" + this.id + " s-box s-" + _.type + " " + _["class"];
        xHtml = "<a style=\"pointer-events: auto;\" class=\"s-close\" href=\"#\">&times;</a>";
        $(this.html).html(xHtml + _.fTitle + " " + _.fText);
        $(_.container).prepend(this.html);
        $('.s-growls-growl .s-close').click(function() {
          return $(this).closest('.s-growls-growl').fadeOut();
        });
        if (_.delay > 0) {
          return fn = (function(delay, id) {
            return setTimeout((function() {
              return $(".s-growls-growl" + id).fadeOut();
            }), delay);
          })(_.delay, this.id);
        }
      }
    });
  })(jQuery);

  $('.s-dropdown').click(function() {
    return $(this).parent().toggleClass('dropdown_open');
  });

  window.clickMenu = function(id, $) {
    var _;
    _ = this;
    if (typeof $ !== 'function') {
      $ = window.$;
    }
    this.menu = {
      menu: $('nav.mainHeader#' + id),
      menu_item: $('#' + id + ' .mainHeader-menu-item > a'),
      menu_item_menu_item: $('#' + id + ' .mainHeader-menu-item-menu-item > a'),
      open: false,
      targeted: false,
      closeMenu: function() {
        $(_.menu.menu).removeClass('clicked');
        _.menu.clearHovers();
        return this.open = false;
      },
      openMenu: function() {
        $(_.menu.menu).addClass('clicked');
        return this.open = true;
      },
      clearHovers: function() {
        $(_.menu.menu_item).removeClass('hover').find('.mainHeader-menu-item-menu').hide();
      },
      init: function() {
        $(_.menu.menu_item_menu_item).mouseover(function() {
          return $(this).focus().click(function() {
            return location.href = $(this).attr('href');
          });
        });
        $(_.menu.menu_item).click(function() {
          if (_.menu.open && _.menu.targeted) {
            return _.menu.closeMenu();
          } else {
            if (_.menu.targeted) {
              $(this).addClass('hover');
            }
            return _.menu.openMenu();
          }
        }).hover(function() {
          return _.menu.targeted = true;
        }, function() {
          _.menu.targeted = false;
          if (!_.menu.open) {
            return _.menu.clearHovers();
          }
        }).mouseover(function() {
          _.menu.clearHovers();
          $(_.menu.menu_item).blur();
          $(this).addClass('hover');
          return false;
        });
        $('html').click(function() {
          if (!_.menu.targeted && _.menu.open) {
            return _.menu.closeMenu();
          }
        });
        $(window).blur(function() {
          return _.menu.closeMenu();
        });
        if ($('iframe').length > 0) {
          $('iframe').contents().keydown(function() {
            return _.menu.closeMenu();
          });
          return $($('iframe').get(0).contentWindow.document).click(function() {
            return _.menu.closeMenu();
          });
        }
      }
    };
    return _.menu.init();
  };

}).call(this);
